name = "AME"
uuid = "9f60cadd-00eb-4e57-b715-beb4ff532cb8"
authors = ["jinshaoliang <18322825326@163.com> and contributors"]
version = "0.0.1"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
