name = "AtomicMassEvaluation"
uuid = "9f60cadd-00eb-4e57-b715-beb4ff532cb8"
authors = ["jinshaoliang <18322825326@163.com> and contributors"]
version = "0.0.2"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"

[compat]
Measurements = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
